kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv2
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-00be83c1f7e83134b
    fsType: ext4
