apiVersion: v1
kind: Service
metadata:
    name: adminmongo-service
spec:
    type: LoadBalancer
    selector:
        app: api
        name: adminmongo
    ports:
        - name: http-1234
          protocol: TCP
          port: 1234
          targetPort: 1234
    externalIPs: 
      - 192.168.137.101
