apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-nfs-pv
  labels:
    app: api
    pv: code-nfs-pv
spec:
  capacity:
    storage: 10GMi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /k8sdata/code
    server: 192.168.136.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10GMi
  selector:
    matchLabels:
      app: api
      pv: code-nfs-pv
