apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    selector:
        matchLabels:
            app: api
            name: nginx
    replicas: 3
    template:
        metadata:
            labels:
                app: api
                name: nginx
        spec:
            containers:
                - name: nginx
                  image: habor.zcx/service/nginx:0.0.1
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                      - containerPort: 443
                  volumeMounts:
                      - name: nginx-config
                        mountPath: /etc/nginx/sites-available
                      - name: web-root
                        mountPath: /var/www
            imagePullSecrets:
                  - name: harborkey1
            volumes:
                - name: nginx-config
                  configMap:
                    name: php-worker
                - name: web-root
                  persistentVolumeClaim:
                    claimName: code-nfs-pvc
