apiVersion: v1
kind: Service
metadata:
    name: php-fpm-service
spec:
    selector:
        app: api
        name: php-fpm
    ports:
        - name: php
          port: 9000
          targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: php-fpm-deployment
spec:
    selector:
        matchLabels:
            app: api
            name: php-fpm
    replicas: 3
    template:
        metadata:
            labels:
                app: api
                name: php-fpm
        spec:
            containers:
                - name: php-fpm
                  image: habor.zcx/service/php-fpm:0.0.1
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: web-root
                        mountPath: /var/www
            imagePullSecrets:
                - name: harborkey1
            volumes:
                - name: web-root
                  persistentVolumeClaim:
                    claimName: code-nfs-pvc