apiVersion: v1
kind: ConfigMap
metadata:
  name: php-worker
  labels:
    app: php-worker
data:
  laravel-worker.conf: |
    [program:laravel-worker-api]
    process_name=%(program_name)s_%(process_num)02d
    command=php /var/www/webapi/artisan queue:work --sleep=3 --tries=3 --daemon
    autostart=true
    autorestart=true
    numprocs=8
    redirect_stderr=true
    
    [program:laravel-worker-admin]
    process_name=%(program_name)s_%(process_num)02d
    command=php /var/www/17duuAdmin/artisan queue:work --sleep=3 --tries=3 --daemon
    autostart=true
    autorestart=true
    numprocs=8
    redirect_stderr=true

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: php-worker-deployment
spec:
    selector:
        matchLabels:
            app: api
            name: php-worker
    replicas: 1 
    template:
        metadata:
            labels:
                app: api
                name: php-worker
        spec:
            containers:
                - name: php-worker
                  image: harbor.yourdomain.com/service/php-worker:0.0.1
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: web-root
                      mountPath: /var/www
                    - name: config-map
                      mountPath: /etc/supervisord.d
            imagePullSecrets:
                  - name: harborkey1
            volumes:
                - name: web-root
                  persistentVolumeClaim:
                    claimName: code-nfs-pvc
                - name: config-map
                  configMap:
                    name: php-worker