apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin-deployment
spec:
    selector:
        matchLabels:
            app: api
            name: phpmyadmin
    replicas: 3
    template:
        metadata:
            labels:
                app: api
                name: phpmyadmin
        spec:
            containers:
                - name: phpmyadmin
                  image: harbor.yourdomain.com/service/phpmyadmin:0.0.1
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
            imagePullSecrets:
                  - name: harborkey1