apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-service
spec:
    type: LoadBalancer
    selector:
        app: api
        name: phpmyadmin
    ports:
        - name: http-80
          protocol: TCP
          port: 8080
          targetPort: 80
    externalIPs: 
      - 192.168.136.101
