# redis-0 PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  labels:
    app: api
    pv: redis-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /k8sdata/data/redis-data
    server: 192.168.137.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: api
      pv: redis-data

