apiVersion: v1
kind: Service
metadata:
    name: redis-out-service
spec:
    type: LoadBalancer
    selector:
      app: api
      name: redis
    ports:
        - name: http-6379
          protocol: TCP
          port: 6379
          targetPort: 6379
    externalIPs: 
      - 192.168.137.101
