apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  labels:
    app: redis
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    aof-use-rdb-preamble yes
    port 6379
    requirepass test