apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      environment: product
  serviceName: "mongo"
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo
        environment: product
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: harbor.yourdomain.com/service/mongo:0.0.4
          imagePullPolicy: Always
          args:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
            - --clusterAuthMode
            - keyFile
            - --keyFile
            - /data/config/mongodb-keyfile
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "091317duu2018"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
              subPath: mongo
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-init-js
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=mongo,environment=product"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongo"
            - name: MONGODB_USERNAME
              value: "admin"
            - name: MONGODB_PASSWORD
              value: "091317duu2018"
            - name: MONGODB_DATABASE
              value: "admin"
      imagePullSecrets:
      - name: harborkey1
      volumes:
      - name: mongo-init-js
        configMap:
          name: mongo-init-js
          defaultMode: 420
          items:
          - key: mongo-init.js
            path: mongo-init.js
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi