apiVersion: v1
kind: Service
metadata:
    name: mongo-out-service
spec:
    type: LoadBalancer
    selector:
        app: mongo
        environment: product
    ports:
        - name: http-27017
          protocol: TCP
          port: 27017
          targetPort: 27017
    externalIPs: 
      - 192.168.137.101
